Updates
Check for composer
Add test
Add php-cs-fixer
Add github actions
Fix some bugs

diff --git a/webdev b/webdev
--- a/webdev
+++ b/webdev
@@ -14,6 +14,7 @@ if test -t 1; then
     ncolors=$(tput colors)
 
     if test -n "$ncolors" && test "$ncolors" -ge 8; then
+        BLINK="$(tput blink)"
         BOLD="$(tput bold)"
         RED="$(tput setaf 1)"
         YELLOW="$(tput setaf 3)"
@@ -22,6 +23,28 @@ if test -t 1; then
         NC="$(tput sgr0)"
     fi
 fi
+
+command -v $DOCKER >/dev/null
+ret=$?
+if [ ! "$ret" == "0" ]; then
+    echo
+    echo "${BOLD}${BLINK}${RED}ERROR${NC}"
+    echo "Command ${YELLOW}${DOCKER}${NC} is missing. Please install it to use this script."
+    echo
+    exit 1
+fi
+
+command -v $COMPOSE >/dev/null
+ret=$?
+if [ ! "$ret" == "0" ]; then
+    echo
+    echo "${BOLD}${BLINK}${RED}ERROR${NC}"
+    echo "Command ${YELLOW}${COMPOSE}${NC} is missing. Please install it to use this script."
+    echo
+    exit 1
+fi
+
+
 
 # Renders a text based list of options that can be selected by the
 # user using up, down and enter keys and returns the chosen option.
@@ -114,6 +137,7 @@ function display_help {
     echo "  ${RED}r${GREEN}un${NC}                     Start Laravel in development mode"
     echo "  ${RED}b${GREEN}uild${NC}                   Build Laravel files for production"
     echo "  ${RED}a${GREEN}rtisan${NC} [command]       Run an artisan command"
+    echo "  ${RED}t${GREEN}est${NC}                    Run laravel tests"
     echo "  ${GREEN}ro${NC}                      ${BLUE}= run + open${NC}"
     echo "  ${GREEN}bo${NC}                      ${BLUE}= build + open${NC}"
     echo
@@ -152,16 +176,21 @@ phpinfo();
 EOF
 }
 
+function add_line_if_missing() { # file text
+    if [ ! -f "$1" ]; then
+        touch "$1"
+    fi
+    sed -i -e '$a\' "$1" # add new line at end of file
+    grep -qxF "$2" "$1" || echo "$2" >> "$1"
+}
+
 function write_gitignore_file {
-    if [ ! -f .gitignore ]; then
-        return
-    fi
-    if [ -z "$(cat .gitignore | grep '/.docker')" ]; then
-        echo '/.docker' >> .gitignore
-    fi
-    if [ -z "$(cat .gitignore | grep 'docker-compose.yml')" ]; then
-        echo 'docker-compose.yml' >> .gitignore
-    fi
+    add_line_if_missing .gitignore "/.docker"
+    add_line_if_missing .gitignore "/docker-compose.yml"
+    add_line_if_missing .gitignore "/.vscode"
+    add_line_if_missing .gitignore "/.php-cs-fixer.cache"
+    add_line_if_missing .gitignore "/vendor"
+    add_line_if_missing .gitignore "/node_modules"
 }
 
 function get_php_version {
@@ -410,7 +439,7 @@ php -r "unlink('composer-setup.php');" && \
 mv composer.phar /usr/local/bin/composer
 RUN docker-php-ext-install zip
 EOF
-    if [ "${PHP_MAIN_VERSION}" == "8" ]; then
+    if [ "${PHP_MAIN_VERSION}" == "8" ] || [ "${PHP_MAIN_VERSION}" == "7" ]; then
     cat <<EOF >> ./.docker/php/Dockerfile
 RUN docker-php-ext-configure gd --with-freetype --with-jpeg && docker-php-ext-install gd
 EOF
@@ -460,6 +489,7 @@ RUN echo '[PHP]' > php.ini && \
 echo 'error_log = /var/www/html/.docker/php/error.log' >> php.ini && \
 echo 'post_max_size = 1024M' >> php.ini && \
 echo 'upload_max_filesize = 256M' >> php.ini && \
+echo 'date.timezone = "UTC"' >> php.ini && \
 echo 'sendmail_path = "/usr/bin/mhsendmail --smtp-addr=webdev-mailhog:1025"' >> php.ini
 USER dev:dev
 WORKDIR /var/www/adminer
@@ -493,37 +523,39 @@ function write_vscode_files {
 }
 EOF
 
-    cat <<EOF > ./.vscode/settings.json
-{
-    "_comment": "This file was generated by $0",
-    "php.format.codeStyle": "Off",
-    "blade.format.enable": true,
-    "bladeFormatter.format.noMultipleEmptyLines": true,
-    "bladeFormatter.format.sortTailwindcssClasses": true,
-    "bladeFormatter.misc.dontShowNewVersionMessage": true,
-    "bladeFormatter.format.sortHtmlAttributes": "alphabetical",
-    "[blade]": {
-        "editor.defaultFormatter": "shufo.vscode-blade-formatter"
-    },
-    "files.trimTrailingWhitespace": true,
-    "files.insertFinalNewline": true,
-   }
-EOF
 }
 
 function write_phpcsfixer_file {
-    cat <<EOF > ./.docker/php-cs-fixer.dist.php
+    if [ -f ./.php-cs-fixer.dist.php ]; then
+        return
+    fi
+
+    echo "${YELLOW}+--------------------------------------------------------+${NC}"
+    echo "${YELLOW}|${NC}                 SuperIndentationFixer                  ${YELLOW}|${NC}"
+    echo "${YELLOW}|${NC}                 =====================                  ${YELLOW}|${NC}"
+    echo "${YELLOW}|${NC}                                                        ${YELLOW}|${NC}"
+    echo "${YELLOW}|${NC} SuperIndentationFixer changes tabs to space in strings ${YELLOW}|${NC}"
+    echo "${YELLOW}|${NC} at beginning of lines for multiline strings. This is   ${YELLOW}|${NC}"
+    echo "${YELLOW}|${NC} a special function for very old projects. For newer    ${YELLOW}|${NC}"
+    echo "${YELLOW}|${NC} projects it may corrupt files.                         ${YELLOW}|${NC}"
+    echo "${YELLOW}+--------------------------------------------------------+${NC}"
+    echo
+    echo -n "Do you want to use \"SuperIndentationFixer\"? [y/n] "
+    read -n 1 YN
+    echo
+    if [ "$YN" == "y" ] || [ "$YN" == "Y" ]; then
+    cat <<EOF > ./.php-cs-fixer.dist.php
 <?php
 
 use PhpCsFixer\AbstractFixer;
+use PhpCsFixer\Config;
+use PhpCsFixer\Finder;
 use PhpCsFixer\FixerDefinition\CodeSample;
 use PhpCsFixer\FixerDefinition\FixerDefinition;
-use PhpCsFixer\Tokenizer\Tokens;
-use PhpCsFixer\Tokenizer\Token;
 use PhpCsFixer\FixerDefinition\FixerDefinitionInterface;
-
-use PhpCsFixer\Config;
 use PhpCsFixer\Runner\Parallel\ParallelConfigFactory;
+use PhpCsFixer\Tokenizer\Token;
+use PhpCsFixer\Tokenizer\Tokens;
 
 class SuperIndentationFixer extends AbstractFixer
 {
@@ -531,28 +563,29 @@ class SuperIndentationFixer extends AbstractFixer
     {
         foreach(\$tokens as \$token) {
             if(\$token->isGivenKind(T_CONSTANT_ENCAPSED_STRING)) {
-                if(strpos(\$token->getContent(),"\t")!==false)
+                if(strpos(\$token->getContent(), "\t") !== false) {
                     return true;
+                }
             }
         }
+
         return false;
     }
 
     public function applyFix(SplFileInfo \$file, Tokens \$tokens): void
     {
-        foreach(\$tokens as \$pos=>\$token) {
+        foreach(\$tokens as \$pos => \$token) {
             if(\$token->isGivenKind(T_CONSTANT_ENCAPSED_STRING)) {
                 \$content = \$token->getContent();
-                if(strpos(\$content,"\t")!==false){
-                    \$lines = explode("\n",\$content);
-                    foreach(\$lines as \$row=>\$line)
-                    {
-                        \$lines[\$row] = preg_replace_callback('/^\s+/',function(\$e){
-                            return str_replace("\t","    ",\$e[0]);
-                        },\$line);
+                if(strpos(\$content, "\t") !== false) {
+                    \$lines = explode("\n", \$content);
+                    foreach(\$lines as \$row => \$line) {
+                        \$lines[\$row] = preg_replace_callback('/^\s+/', function (\$e) {
+                            return str_replace("\t", '    ', \$e[0]);
+                        }, \$line);
                     }
-                    \$content = implode("\n",\$lines);
-                    \$tokens[\$pos] = new Token([T_CONSTANT_ENCAPSED_STRING,\$content]);
+                    \$content = implode("\n", \$lines);
+                    \$tokens[\$pos] = new Token([T_CONSTANT_ENCAPSED_STRING, \$content]);
                 }
             }
         }
@@ -560,7 +593,7 @@ class SuperIndentationFixer extends AbstractFixer
 
     public function getDefinition(): FixerDefinitionInterface
     {
-        return new FixerDefinition('Fixes Tabs on line beginnings in strings',[new CodeSample('no sample')]);
+        return new FixerDefinition('Fixes Tabs on line beginnings in strings', [new CodeSample('no sample')]);
     }
 
     public function getPriority(): int
@@ -582,19 +615,158 @@ return (new Config())
     ->setRules([
         '@PSR12' => true,
         '@PhpCsFixer' => true,
-        'yoda_style' => ['equal'=>false,'identical'=>false,'less_and_greater'=>false],
+        'yoda_style' => ['equal' => false, 'identical' => false, 'less_and_greater' => false],
+        'concat_space' => ['spacing' => 'one'],
         'increment_style' => false,
-        'blank_line_before_statement' => false,
+        'semicolon_after_instruction' => false,
         'indentation_type' => true,
+        'single_space_around_construct' => false,
         'line_ending' => true,
+        'echo_tag_syntax' => ['format' => 'short', 'long_function' => 'print'],
+        'no_mixed_echo_print' => ['use' => 'print'],
         'SuperIndentationFixer/tabtospace' => true,
     ])
-    ->setIndent("    ")
-    ->setLineEnding("\n");
+    ->setIndent('    ')
+    ->setLineEnding("\n")
+    ->setFinder((new Finder())->in(__DIR__))
+;
 EOF
+    else
+    cat <<EOF > ./.php-cs-fixer.dist.php
+<?php
 
+use PhpCsFixer\Config;
+use PhpCsFixer\Finder;
+use PhpCsFixer\Runner\Parallel\ParallelConfigFactory;
+
+return (new Config())
+    ->setParallelConfig(ParallelConfigFactory::detect())
+    ->setRules([
+        '@PSR12' => true,
+        '@PhpCsFixer' => true,
+        'yoda_style' => ['equal' => false, 'identical' => false, 'less_and_greater' => false],
+        'concat_space' => ['spacing' => 'one'],
+        'increment_style' => false,
+        'semicolon_after_instruction' => false,
+        'indentation_type' => true,
+        'single_space_around_construct' => false,
+        'line_ending' => true,
+        'echo_tag_syntax' => ['format' => 'short', 'long_function' => 'print'],
+        'no_mixed_echo_print' => ['use' => 'print'],
+    ])
+    ->setIndent('    ')
+    ->setLineEnding("\n")
+    ->setFinder((new Finder())->in(__DIR__))
+;
+EOF
+    fi
 }
 
+function write_github_action_file {
+    if [ -f ./.docker/githubaction ]; then
+        return
+    fi
+
+    if [ ! -d ./.git ]; then
+        return
+    fi
+
+    if [ -f ./.github/workflows/php-cs-fixer.yml ]; then
+        return
+    fi
+
+    echo -n "Do you want to add an automatic formatting script for GitHub? [y/n] "
+    read -n 1 YN
+    echo
+    if [ "$YN" == "y" ] || [ "$YN" == "Y" ]; then
+        write_phpcsfixer_file
+        mkdir -p ./.github/workflows
+        cat <<EOF > ./.github/workflows/php-cs-fixer.yml
+name: Check & fix styling
+
+on:
+  push:
+    branches: [main]
+  pull_request:
+    branches: [main]
+
+jobs:
+  php-cs-fixer:
+    runs-on: ubuntu-latest
+
+    permissions:
+      contents: write
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          ref: \${{ github.head_ref }}
+
+      - name: Run PHP CS Fixer
+        uses: docker://oskarstark/php-cs-fixer-ga
+        with:
+          args: --config=.php-cs-fixer.dist.php --allow-risky=yes
+
+      - name: Commit changes
+        uses: stefanzweifel/git-auto-commit-action@v5
+        with:
+          commit_message: Fix styling
+EOF
+    fi
+    mkdir -p ./.docker
+    touch ./.docker/githubaction
+}
+
+function init_git_repo {
+    if [ -f ./.docker/gituse ]; then
+        return
+    fi
+
+    if [ -d ./.git ]; then
+        return
+    fi
+
+    echo -n "Do you want to use GIT for this project? [y/n] "
+    read -n 1 YN
+    echo
+    if [ "$YN" == "y" ] || [ "$YN" == "Y" ]; then
+        options=("Create a new local repository" "Check out existing repository")
+        select_option "${options[@]}"
+        GIT=$?
+        if [ "$GIT" == "0" ]; then
+            git init
+        fi
+        if [ "$GIT" == "1" ]; then
+            echo -n "Enter path of repository: "
+            read REPO
+            git clone "$REPO" git_temp
+            if [ ! -d git_temp ]; then
+                stop_if_up
+                echo "${RED}Checkout failed. Try again or use a new repository.${NC}"
+                exit 1
+            fi
+            move_to_owner git_temp
+        fi
+    fi
+    mkdir -p ./.docker
+    touch ./.docker/gituse
+}
+
+function move_to_owner {
+    if [ ! -d "$1" ]; then
+        return
+    fi
+    cd "$1"
+    if [ "$2" == "git" ]; then
+        find -mindepth 1 -maxdepth 1 ! -name .git -exec cp -r -f {} ../ \;
+    else
+        find -mindepth 1 -maxdepth 1 -exec cp -r -f {} ../ \;
+    fi
+    cd ..
+    rm -rf "$1"
+
+}
 
 function confirm {
     echo "${YELLOW}All files will be deleted!${NC}"
@@ -623,8 +795,16 @@ function get_webdev_dir {
 
 function goto {
     if [ ! "$(pwd)" == "$1" ]; then
-        cd $1
-        echo "${YELLOW}Web development folder: ${NC}$(pwd)"
+        echo "${RED}Web development folder detected!${NC}"
+        echo "${YELLOW}You are here: ${NC}$(pwd)"
+        echo "${YELLOW}Web development here: ${NC}$1"
+        echo -n "${GREEN}Do you want to change? [y/n] "
+        read -n 1 YN
+        echo
+        if [ "$YN" == 'y' ] || [ "$YN" == 'Y' ]; then
+            cd $1
+            echo "${YELLOW}You are now here: ${NC}$(pwd)"
+        fi
     fi
 }
 
@@ -658,6 +838,8 @@ if [ "$cmd" == "up" ] || [ "$cmd" == "u" ]; then
         fi
     fi
 
+    init_git_repo
+
     echo "${YELLOW}Starting webdev containers...${NC}"
     write_docker_compose
     write_docker_file_php
@@ -677,7 +859,11 @@ if [ "$cmd" == "up" ] || [ "$cmd" == "u" ]; then
                 if [ ! -f .env ]; then
                     cp .env.example .env
                 fi
-                ${EXEC} sed -i 's/MAIL_HOST=.*/MAIL_HOST=mailhog/' .env
+                ${EXEC} sed -i 's/MAIL_HOST=.*/MAIL_HOST=webdev-mailhog/' .env
+                ${EXEC} sed -i 's/MAIL_PORT=.*/MAIL_PORT=1025/' .env
+                ${EXEC} sed -i 's/MAIL_USERNAME=.*/MAIL_USERNAME=null/' .env
+                ${EXEC} sed -i 's/MAIL_PASSWORD=.*/MAIL_PASSWORD=null/' .env
+                ${EXEC} sed -i 's/MAIL_ENCRYPTION=.*/MAIL_ENCRYPTION=null/' .env
                 echo laravel > ./.docker/framework
                 exit 0
             fi
@@ -711,6 +897,7 @@ if [ "$cmd" == "up" ] || [ "$cmd" == "u" ]; then
         fi
         $0 install
     fi
+    write_github_action_file
     FRAMEWORK=$(cat ./.docker/framework)
     if [ "$FRAMEWORK" == "laravel" ]; then
         laravel_set_database
@@ -795,7 +982,7 @@ elif [ "$cmd" == "install" ] || [ "$cmd" == "i" ]; then
             stop_if_up
             rm -rf ./.docker
         fi
-        find -maxdepth 1 ! -name . ! -name .git -exec rm -rf {} +
+        find -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
     fi
     mkdir -p ./.docker
     touch ./.docker/framework
@@ -813,11 +1000,17 @@ elif [ "$cmd" == "install" ] || [ "$cmd" == "i" ]; then
         else
             ${EXEC} /home/dev/.config/composer/vendor/bin/laravel new --database sqlite lv_temp
         fi
-        cd lv_temp
-        find -maxdepth 1 ! -name . ! -name .git -exec mv -f {} ../ \;
-        cd ..
-        rm -rf lv_temp
-        ${EXEC} sed -i 's/MAIL_HOST=.*/MAIL_HOST=mailhog/' .env
+        if [ ! -d lv_temp ]; then
+            stop_if_up
+            echo "${RED}Installation failed. Try again.${NC}"
+            exit 1
+        fi
+        move_to_owner lv_temp git
+        ${EXEC} sed -i 's/MAIL_HOST=.*/MAIL_HOST=webdev-mailhog/' .env
+        ${EXEC} sed -i 's/MAIL_PORT=.*/MAIL_PORT=1025/' .env
+        ${EXEC} sed -i 's/MAIL_USERNAME=.*/MAIL_USERNAME=null/' .env
+        ${EXEC} sed -i 's/MAIL_PASSWORD=.*/MAIL_PASSWORD=null/' .env
+        ${EXEC} sed -i 's/MAIL_ENCRYPTION=.*/MAIL_ENCRYPTION=null/' .env
         ${EXEC} php artisan migrate
         echo laravel > ./.docker/framework
     fi
@@ -845,10 +1038,7 @@ elif [ "$cmd" == "install" ] || [ "$cmd" == "i" ]; then
     fi
     if [ "$FW" == "4" ]; then
         ${EXEC} git clone https://github.com/hakimel/reveal.js rv_temp
-        cd rv_temp
-        find -maxdepth 1 ! -name . ! -name .git -exec mv -f {} ../ \;
-        cd ..
-        rm -rf rv_temp
+        move_to_owner rv_temp
         mkdir -p ./public
         mkdir -p ./assets/images
         mkdir -p ./assets/sounds
@@ -919,6 +1109,15 @@ elif [ "$cmd" == "build" ] || [ "$cmd" == "b" ]; then
         echo "${RED}No buildable framework installed!${NC}"
         exit 1
     fi
+elif [ "$cmd" == "test" ] || [ "$cmd" == "t" ]; then
+    FRAMEWORK=$(cat ./.docker/framework)
+    if [ "$FRAMEWORK" == "laravel" ]; then
+        start_if_down
+        ${EXEC} php artisan test
+    else
+        echo "${RED}No Laravel framework installed!${NC}"
+        exit 1
+    fi
 elif [ "$cmd" == "export" ] || [ "$cmd" == "x" ]; then
     FRAMEWORK=$(cat ./.docker/framework)
     if [ "$FRAMEWORK" == "reveal.js" ]; then
@@ -969,13 +1168,14 @@ elif [ "$cmd" == "format" ] || [ "$cmd" == "f" ]; then
         shift 1
     done
 
-    if [ "$c_files" == "" ]; then
-        c_files=$RELPATH
-    fi
+    #if [ "$c_files" == "" ]; then
+    #    c_files=$RELPATH
+    #fi
+
     if [ "$userules" == "1" ]; then
         ${EXEC} ./vendor/bin/php-cs-fixer $c_cmd --verbose $c_opts $c_files
     else
-        ${EXEC} ./vendor/bin/php-cs-fixer $c_cmd --verbose --config ./.docker/php-cs-fixer.dist.php $c_opts $c_files
+        ${EXEC} ./vendor/bin/php-cs-fixer $c_cmd --verbose --config ./.php-cs-fixer.dist.php $c_opts $c_files
     fi
 elif [ "$cmd" == "bo" ]; then
     start_if_down
@@ -995,9 +1195,9 @@ elif [ "$cmd" == "remove" ]; then
         $0 down
         rm -rf .docker
         rm -f .vscode/launch.json
-        rm -f .vscode/settings.json
         rmdir --ignore-fail-on-non-empty .vscode
         rm -f docker-compose.yml
+        rm -f .php-cs-fixer.cache
     fi
 elif [ "$cmd" == "cleanup" ]; then
     echo "${YELLOW}All docker containers and images will be removed from system${NC}"
